luke-josh-project/Controllers/PokerController.cs
using luke_josh_project.Data;
using luke_josh_project.Models;
using luke_josh_project.Models.Enums;
using luke_josh_project.Models.ViewModels;
using luke_josh_project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace luke_josh_project.Controllers
{
    public class PokerController : Controller
    {
        PokerService _pokerService = new PokerService();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Stats()
        {
            ViewBag.Message = "A page to contain stats";

            //grab the data
            List<ScoreboardModel> scoreboard = new List<ScoreboardModel>();

            PokerViewModel viewModel = _pokerService.GetPokerData();
            List<Data.PokerResult> results = _pokerService.GetResults();
            List<Data.PokerMatch> matches = _pokerService.GetMatches();


            //loop through data and map it to model
            foreach (var user in viewModel.Users)
            {
                int totalIncoming = 0;
                int totalOutgoings = 0;
                int totalWins = 0;
                var userResults = results.Where(x => x.PokerUserId == user.Id).ToList();

                foreach (var result in userResults)
                {
                    var currentMatch = matches.Where(x => x.Id == result.PokerMatchId).FirstOrDefault();
                    var matchResults = results.Where(x => x.PokerMatchId == currentMatch.Id);
                    totalOutgoings += currentMatch.BuyIn;

                    //if this user won
                    if (result.Placing == (int)Enums.Placing.First)
                    {
                        totalWins += 1;
                        totalIncoming += (currentMatch.BuyIn * matchResults.Count());
                        if (!currentMatch.IsWinnerTakesAll)
                        {
                            //second place gets money back
                            totalIncoming -= currentMatch.BuyIn;
                        }
                    }
                }

                ScoreboardModel userScore = new ScoreboardModel();
                userScore.Name = user.Name;
                userScore.GamesPlayed = userResults.Count;
                userScore.TotalWins = totalWins;
                userScore.TotalIncomings = totalIncoming;
                userScore.TotalOutgoings = totalOutgoings;
                userScore.Profit = totalIncoming - totalOutgoings;
                userScore.TotalLosses = userResults.Count - totalWins;
                userScore.WinPercentage = Math.Round((totalWins * 100.0) / userResults.Count);

                scoreboard.Add(userScore);
            }

            viewModel.Scoreboard = scoreboard;

            return View(viewModel);
        }

        public void GetScoreboard()
        {
            ScoreboardModel scoreboard = new ScoreboardModel();

        }

        public ActionResult Game()
        {
            GameViewModel model = new GameViewModel();
            PokerService pokerService = new PokerService();
            var data = pokerService.GetPokerData();
            model.Users = data.Users;
            return View(model);
        }


        public void AddGameResult(string order, int buyIn, bool winnerTakes)
        {
            List<int> results = new JavaScriptSerializer().Deserialize<List<int>>(order);
            List<PokerResult> resultsObj = new List<PokerResult>();

            PokerMatch match = new PokerMatch
            {
                Date = DateTime.Now,
                IsWinnerTakesAll = winnerTakes,
                BuyIn = buyIn
            };            

            for (int i = 0; i < results.Count; i++)
            {
                resultsObj.Add(new PokerResult
                {
                    Placing = i + 1,
                    PokerUserId = results[i],
                    PokerMatchId = 0
                });
            }

            _pokerService.AddGameResult(match, resultsObj);
        }
    }
}

luke-josh-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("On the flop", "Index", "Poker", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Stats", "Stats", "Poker")</li>
                    <li>@Html.ActionLink("Manage", "Game", "Poker")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - On the flop</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script src="~/Scripts/JS/site.js"></script>
<script>
    var site = "";
    $(function () {
        site = new Site();
    });
</script>